# Generated by Django 4.1.3 on 2022-12-04 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hesap',
        ),
    ]
