# Generated by Django 4.1.3 on 2022-12-04 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_alter_hesap_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='hesap',
            name='takipçi',
            field=models.ManyToManyField(related_name='takipçi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hesap',
            name='resim',
            field=models.FileField(blank=True, default='default.webp', upload_to='hesaplar/'),
        ),
    ]
